# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculate.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63\x61lculate.proto\"(\n\x17SamplingVarianceRequest\x12\r\n\x05\x63hunk\x18\x01 \x03(\x01\"<\n\x15SamplingVarianceReply\x12\x0b\n\x03sum\x18\x01 \x01(\x01\x12\x16\n\x0esum_of_squares\x18\x02 \x01(\x01\x32Z\n\x10SamplingVariance\x12\x46\n\x12PerformCalculation\x12\x18.SamplingVarianceRequest\x1a\x16.SamplingVarianceReplyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculate_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SAMPLINGVARIANCEREQUEST._serialized_start=19
  _SAMPLINGVARIANCEREQUEST._serialized_end=59
  _SAMPLINGVARIANCEREPLY._serialized_start=61
  _SAMPLINGVARIANCEREPLY._serialized_end=121
  _SAMPLINGVARIANCE._serialized_start=123
  _SAMPLINGVARIANCE._serialized_end=213
# @@protoc_insertion_point(module_scope)
